apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysite
    app.kubernetes.io/managed-by: Helm
  name: mysite
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: python-app
  type: NodePort
status:
  loadBalancer: {}